version: "3"
services:
  back:
    image: hyhyena/payout:latest
    ports:
      - 8080:8080

  gateway:
    image: nginx:latest
    ports:
      - 8085:8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../front/dist:/usr/share/nginx/www